dist: trusty

language: node_js
node_js:
  - 8
  - node

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache:
  yarn: true
  directories:
    - ~/.nvm
    - ~/.cache
    - node_modules

before_install:
  - npm install -g yarn

install:
  - yarn install --frozen-lockfile

script:
  - yarn lint

jobs:
  include:
    - stage: Release
      if: branch = master AND type = push
      node_js: node
      script: yarn semantic-release

