sudo: false
dist: trusty

language: node_js
node_js:
  - 8
  - node

cache:
  yarn: true
  directories:
    - ~/.nvm
    - ~/.cache
    - node_modules

before_install:
  - npm install -g yarn

install:
  - yarn

script:
  - yarn lint
