sudo: false
dist: trusty

language: node_js
node_js:
  - 8

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache:
  yarn: true
  directories:
    - ~/.nvm
    - ~/.cache
    - node_modules

before_install:
  - npm install -g yarn

install:
  - yarn install --frozen-lockfile

script:
  - yarn lint

after_success:
  - yarn travis-deploy-once "yarn semantic-release"
