name: Release

on:
    push:
        branches:
            - master

env:
    CI: true

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Install Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 10.x

            -   run: yarn install --frozen-lockfile

            -   run: yarn semantic-release
                env:
                    NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
